# Generated by Django 4.2.5 on 2023-09-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
